services:
  mkdocs:
    image: shafish/mkdocs-material:9.6.20
    container_name: mkdocs-material
    ports:
      - "8000:8000"
    volumes:
      - ./:/docs
    restart: unless-stopped


"provider": {
  "nvidia": {
   "npm": "@ai-sdk/openai-compatible",
   "name": "NVIDIA",
   "options": {
    "baseURL": "https://integrate.api.nvidia.com/v1"
   },
   "models": {
    "z-ai/glm4.7": {
     "name": "GLM 4.7"
    },
    "minimaxai/minimax-m2.1": {
      "name": "MiniMax M2.1"
    }
   }
  }
 }